### ISSUE TITLE
Missing RxJava 1 and 2 javadocs

### ISSUE THREAD

**Issue by adandersen** [vietj/reactive-pg-client#48]
Hello,

I am keen to try this as a replacement for our postgres driver with com.impossible for pg_notify support. RxJava is said to be supported, but I do not see anywhere Rx methods or a wrapper Rx library like RxJava for Vert.x. What am I missing?

Thank you.

**Comment by vietj** [comment]
the methods are generated by the generation process so you cannot see them in the source code, you can find them in the javadoc : http://www.julienviet.com/reactive-pg-client/apidocs/index.html?com/julienviet/pgclient/PgCursor.html

**Comment by vietj** [comment]
so I think it should at least be in javadoc
