### ISSUE TITLE
How to create a table using a PgClient

### ISSUE THREAD

**Issue by omar753sahl** [vietj/reactive-pg-client#49]
How do I execute a statement like this `CREATE TABLE IF NOT EXISTS movies (id SERIAL, name varchar(100), release varchar(10))` using a PgClient?

**Comment by vietj** [comment]
you just execute a simple query:

```
client.query(myStatement, ar -> {
  if (ar.succeeded()) {
  } else {
    System.out.println("Failure: " + ar.cause().getMessage());
  }
});
```
