### ISSUE TITLE
Postgres connections are still allocated with process_id even though connection has been closed.

### ISSUE THREAD

**Issue by bino013** [vietj/reactive-pg-client#5]
Hi,

I'm currently encountering a problem with postgresql connection when I use the reactive-pg-client. It seems that the connection allocated for the client when I made a query are still running as process in postgresql server, even though I am closing the connections via `PgConnection.close` method.   I have verify this thru this query postgres query, 

`select pid as process_id, 
       usename as username, 
       datname as database_name, 
       client_addr as client_address, 
       application_name,
       backend_start,
       state,
       state_change
from pg_stat_activity;` 

and after sometime we will be encountering this postgres error:

`Connecting to the PostgreSQL database...
      FATAL:  remaining connection slots are reserved for non-replication superuser connections`

Here is some of my sample codes:

``` 
conn.query(query, handler -> {
      if (handler.succeeded()) {
                PgRowSet result = handler.result();
                if (result.rowCount() == 1) {
                      someMethod
                } else {
                    errorMethod()
                }
            } else {
                errorMethod()
            }
            conn.close();
});
```

 I hope you could help me. Thank you!

**Comment by BillyYccc** [comment]
Hi, calling `PgConnection#close` will not shutdown the connection immediately, it will make sure all the pending commands are sending to the server, you can set a `PgConnection#closeHandler` on the connection and will be notified when the physical connection is closed.

**Comment by bino013** [comment]
Hi @BillyYccc,

What should be proper handling to ensure that all the connection used by the client will be re-allocated to new query calls? So I will not be encountering `Connecting to the PostgreSQL database...       FATAL:  remaining connection slots are reserved for non-replication superuser connections`. 

Is there a duration before a physical connection is closed? Is there is how many sec/millisec and is it configurable?

**Comment by BillyYccc** [comment]
> all the connection used by the client will be re-allocated to new query calls

I don't understand what this means, can you give more details?

> Is there a duration before a physical connection is closed? Is there is how many sec/millisec and is it configurable?

yes, that depends on how many commands are pending and it may take some time for these commands to be processed by the server.

**Comment by BillyYccc** [comment]
Maybe we should add a `PgConnection#terminate` method which just sends a terminate message to the server ignoring the pending commands so the connection is immediately shutdown by the server. @vietj

**Comment by bino013** [comment]
Hi, @BillyYccc,

I tried sending queries again in the postgresql db vai the reactive-pg-cleint again around 11am. So base on your statement that physical connection it should be closed by now. But it seems its not. Please the table result below:
<img width="713" alt="Screen Shot 2019-05-27 at 12 45 00 PM" src="https://user-images.githubusercontent.com/3414677/58396000-4e092400-807d-11e9-8a08-c578d54f58bb.png">

You will see that there are still running and idle postgres connection used the reactive-pg-client. It seems that the physical connection is not closing.

**Comment by bino013** [comment]
By the way, this is the query I used to check the connection.

```
select pid as process_id,  
       application_name,
       backend_start,
       state,
       state_change
from pg_stat_activity;```

**Comment by BillyYccc** [comment]
Can you give a full runnable reproducer? a small project would be fine.

**Comment by bino013** [comment]
Here is the sample project.

Please take note I am closing the PgPool when the service is terminated, since I assume that when PgPool class handles the connection pooling, when a connection is close via `PgConnection.close`, it will be reused again, when I call `PgPool.getConnection`.

[sample-project.zip](https://github.com/vietj/reactive-pg-client/files/3221971/sample-project.zip)

**Comment by bino013** [comment]
Hi @BillyYccc,

Is there's a way to set the max no of connection can reactive-pg-client can be use? I think that may be one of the solution.

**Comment by BillyYccc** [comment]
`maxsize` means the max number of connections the pool will hold, if your pool is saturated(which means maxsize connections in the pool are busy) then your new request for connection will enter in waiting state, and you can set `maxWaitQueueSize` to control the waiting number.

 If you are calling `PgConnection#close` of the connection from the pool, then connection will not be closed and only get released to the pool, so in your code the connection is not closed but released back to the pool. I think you can find more info in the documentation https://reactiverse.io/reactive-pg-client/guide/java/.

**Comment by bino013** [comment]
Ah okay @BillyYccc. I think I've might been identify the problem. It seems that max-connection of postgres server is less than the number set in maxSize. I'll be increasing the max-connection in postgres server to accommodate the maxSize connection needed by our service. I'll be closing the issue now and observe my fix first.

Thank you very much for patiently answering my inquiries :)
