### ISSUE TITLE
Tuple with more than 6 argument?

### ISSUE THREAD

**Issue by willks** [vietj/reactive-pg-client#59]
Hi,
  Did not know if it was the best place to ask a question, but I could not find somewhere else. So I'm building a fully reactive app using gRPC, and this driver was of interest to me. The syntax is small and concise.

The issue I have is that I'm doing an insert, and the insert has more than 6 tuples. I want to use bindings as I don't like encoding values in the string:

Code:

```
public Single<Identity> create(Identity identity) {
    long timestamp = System.currentTimeMillis();
    identity.setCreationTimestamp(timestamp);
    identity.setModificationTimestamp(timestamp);
    identity.setIdentityId(UUID.randomUUID());
    Single<PgResult<Row>> insert = db.rxPreparedQuery(
            "insert into principal(id, identityId, name, email, creationTimestamp, modificationTimestamp, active) " +
                    "values ($1, $2, $3, $4, $5, $6, $7) returning *" ,
            Tuple.of(identity.getId(),
                    identity.getIdentityId().toString(),
            identity.getName(),
            identity.getEmail(),
            identity.getCreationTimestamp(),
            identity.getModificationTimestamp()));
    return insert.map(new Function<PgResult<Row>, Identity>() {
        @Override
        public Identity apply(PgResult<Row> rowPgResult) throws Exception {
            // We only expect one result
            PgResult<Row> next = rowPgResult.next();
            Row next1 = next.iterator().next();
            return mapRow(next1);
        }
    });
}
```

However, I run out of tuple arguments for the 7th parameter! Any suggestions?

Thanks

**Comment by vietj** [comment]
I think we should add var-args to the Tuple builder

**Comment by vietj** [comment]
the is a varargs builder `Tuple#of(Object... elements)`

**Comment by willks** [comment]
Thanks for that! I'll give it another shot now. Looks like a promising project!

**Comment by willks** [comment]
Apologies - One more question on the topic. Using the latest release, I can't find that varargs method. Am I missing something or using a wrong version? I'm using the "reactivex" flavour, not the default.

THanks

**Comment by vietj** [comment]
ah, it is normal then, you can workaround using:

```
new com.julienviet.reactivex.pgclient.Tuple(Tuple.of(varargs));
```

In the next version of Vert.x (3.6), we will allow the `@GenIgnore` methods to be present on the rxified API.

**Comment by willks** [comment]
@vietj Worked great! Thanks again. Please close at will

**Comment by perttuk** [comment]
I'm having similar problem.

This is my SQL statement:
```
insert into tbl (cmc_id, name) values ($1, $2)
```

preparedBatch call:
```
pgPool.rxPreparedBatch("sql", batch)
```

and this is how the batch is built:
```
private io.reactiverse.reactivex.pgclient.Tuple createTuple(Object row) {
    return io.reactiverse.reactivex.pgclient.Tuple.of(io.reactiverse.pgclient.Tuple.of(
            row.id(),
            row.name()
    ));
}
```

and the error is:
```
io.vertx.core.impl.NoStackTraceThrowable: Values [null] cannot be coerced to [Number, String]
```
