### ISSUE TITLE
Numeric as Unaltered BigDecimal

### ISSUE THREAD

**Issue by cretz** [vietj/reactive-pg-client#61]
I am evaluating this library as an alternative to a couple of [other](https://github.com/mauricio/postgresql-async) [libraries](https://github.com/alaisi/postgres-async-driver) that have stalled. I am reading: https://github.com/vietj/reactive-pg-client/blob/09c07499bbe2925ade22b3b23a46552d08bcd3ea/src/main/java/com/julienviet/pgclient/impl/codec/DataType.java#L188-L203 and I see that it turns it to a double or big integer which seems very unnatural. As noted there I lose precision. Also, to work with it properly on the client side, I have to test for `BigInteger` or `Double` to change it back to a common type even though it is a common type on the postgres side.

Is there any chance to get `BigDecimal` support instead or is there anything I am misreading? Or can I use a custom data type? I hope the project is early enough that these kinds of changes aren't too harmful.

**Comment by vietj** [comment]
@cretz yes I think we should do that, I added the comment myself as I found this part dubious, what's your opinion @EmadAlblueshi ?

**Comment by EmadAlblueshi** [comment]
Hi @cretz @vietj  yes the `BigDecimal` should be supported for `Numeric` data type. Hopefully this will be added very soon.

**Comment by cretz** [comment]
Might need to revisit the types altogether and it'd sure be nice if one could add/override them at runtime. Quick notes:

1. Why is int8 a long but int8 array an int array?
1. Don't forget numeric arrays deserve to be big decimal too
1. Why are so many other array types just objects (e.g. text, name, time, uuid, etc) and not arrays of the types of the single-version counterparts?
1. Looks like you use pg embedded, so probably worth testing every data type if you don't already

**Comment by vietj** [comment]
@cretz yes we should support mapping different runtime type for a given pg type, we need to come up with an API for that I think

we definitely lack of support for array types, perhaps you can help us improve it and contribute ?

**Comment by gunnarmorling** [comment]
Just came across this one through a link on Reddit; we also had to deal with mapping numeric columns in [Debezium's Postgres connector](http://debezium.io/docs/connectors/postgresql/).

One thing to keep in mind is that Postgres supports the special values `NaN`, `Infinity` and `-Infinity` for numeric columns, which can't be mapped to `BigDecimal` AFAIK. We addressed that by optionally mapping numerics to String which naturally can represent these values.

**Comment by EmadAlblueshi** [comment]
Hi @gunnarmorling 
The current issue for NUMERIC data type which allows NaN only according to PostgreSQL documentation and you are right it can't be mapped to BigDecimal.

**Comment by vietj** [comment]
we could keep as string in the tuple and have Tuple#getBigDecimal convert the String to BigDecimal ?

**Comment by vietj** [comment]
another way would be to have a wrapper that extends Number that keeps the String and then have this converted easily to big decimal using the string constructor

**Comment by gunnarmorling** [comment]
Yes, I think that'd be sensible and pretty much the same what the regular
JDBC driver is doing. And if one calls getBigDecimal() but it's one of the
special values, an exception would be raised.

**Comment by vietj** [comment]
I've created this issue https://github.com/vietj/reactive-pg-client/issues/70

**Comment by vietj** [comment]
@gunnarmorling can you have a  look https://github.com/vietj/reactive-pg-client/pull/71 ?

**Comment by cretz** [comment]
As an update, I wrote a separate driver at https://github.com/cretz/pgnio to avoid some of these things and the external dependencies.

**Comment by vietj** [comment]
@cretz that was the right thing to do
