### ISSUE TITLE
Behaviour of exhausted pool?

### ISSUE THREAD

**Issue by willks** [vietj/reactive-pg-client#75]
Hi,
  I'm getting an issue when using the connection pool (that is, without manually managing my own connection). The issue is that if more than 10 concurrent requests are excited against a pool that only has 10 connections, there seems to be a deadlock condition and nothing ever happens. 

I have updated my code from a previous test in order to demonstrate this. The variable " iterationCount)" can be used to test the condition. To make the test work, change it to iteractionCount = 5.

Please checkout project and issue a "grade run" to replicate

https://github.com/willks/pgtest

**Comment by vietj** [comment]
will have a look

**Comment by vietj** [comment]
I think your test is incorrect, you are using `pool#getConnection` and never close the connection you get, in addition you use `pool#query` and this method will also borrow a connection from the pool although the test should use the connection obtained from the `getConnection` method.

**Comment by willks** [comment]
Apologies. I fixed test by removing getConnection. But you're right, the pooling behaviour is handled correctly. However, for the previous scenario - yes a test would be good (or an error) to help us find out leaks in code.

Apologies for time wasted.
