### ISSUE TITLE
Question: Example on storing JSONB column with prepared query

### ISSUE THREAD

**Issue by willks** [vietj/reactive-pg-client#76]
Hi,
  I've been trying to store an embedded jsonb object, but column is always null and console prints
"Data type 3802 does not support binary encoding". I've tried saving as a "JsonObject" type - and the string representation of the JSON. Is there an example on how to do this that I missed? I searched through tests and examples (but probably not diligently enough!)

**Comment by EmadAlblueshi** [comment]
JSONB not yet implemented for prepared query.

**Comment by willks** [comment]
I need it myself, so I'll have a look at it. Thanks for reply. Closing as it's already tracked
